### ISSUE TITLE
Default install not working on CentOS 7

### ISSUE THREAD

**Issue by francoisprunier** [sequenceiq/cloudbreak-deployer#96]
Hi,

I've been trying to setup cloudbreak on Centos 7 and I can't get it to run properly. I have the UI working, but it won't let me connect. It says `Client cannot access resource server.`

There seem to be a problem where the identity container that cannot connect to the cbdb container.

```
docker logs cbreak_sultans_1
+ cd /sultans
+ node main.js
UAA server location: http://backend:8089
Server listening on port 3000 in development mode
POST login.do - Client cannot access resource server. Check UAA address.
POST login.do - Client cannot access resource server. Check UAA address.
```

On the identity server I get this:

```
[2015-07-29 13:33:06.446] cloudfoundry-identity-uaa - ???? [localhost-startStop-1] .... ERROR --- DispatcherServlet: Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [spring/data-source.xml]: Invocation of init method failed; nested exception is com.googlecode.flyway.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:195)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:703)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:760)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:482)
        at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:658)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:624)
        at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:672)
        at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:543)
        at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:484)
        at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
        at javax.servlet.GenericServlet.init(GenericServlet.java:158)
        at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1284)
        at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1197)
        at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1087)
        at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5229)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5516)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1083)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1880)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.googlecode.flyway.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
        at com.googlecode.flyway.core.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
        at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1174)
        at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1681)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1620)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
        ... 32 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:152)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
        at org.postgresql.jdbc3.Jdbc3Connection.<init>(Jdbc3Connection.java:24)
        at org.postgresql.Driver.makeConnection(Driver.java:393)
        at org.postgresql.Driver.connect(Driver.java:267)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278)
        at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:486)
        at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:144)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:116)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:103)
        at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
        at com.googlecode.flyway.core.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
        ... 41 more
Caused by: java.io.EOFException
        at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:276)
        at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:271)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108)
        ... 57 more
Jul 29, 2015 1:33:06 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive /tomcat/webapps/ROOT.war has finished in 4,955 ms
Jul 29, 2015 1:33:06 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-8080"]
Jul 29, 2015 1:33:06 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["ajp-bio-8009"]
Jul 29, 2015 1:33:06 PM org.apache.catalina.startup.Catalina start
INFO: Server startup in 5058 ms
```

The db container is fine though:

```
docker logs cbreak_cbdb_1
[INFO] previous DB found, leave it ...
LOG:  database system was interrupted; last known up at 2015-07-29 12:50:15 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 0/1780FB8
LOG:  redo is not required
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

It looks like ambassador is relaying the connection properly, I can't see why though.

Any help would be appreciated !

Thanks,
François

**Comment by biharitomi** [comment]
Hi @francoisprunier ,

The Identity server(UAA) could not connect to its database that called 'cbreak_uaadb...' and not to the database of Cloudbreak.
I do not know what cause the connection problem. So please list the docker containers with 'docker ps -a' and try to get the logs of the 'cbreak_uaadb_1'.

Please let us know if you need any help!

Br,
Tamas

**Comment by francoisprunier** [comment]
Hi @biharitomi,

Thanks for the quick reply. Sorry about the confusion, it's indeed the uaadb that it's supposed to connect to.

Here's the output of docker ps -a

```
docker ps -a
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS                     PORTS                                                                                                  NAMES
14e8f7c0eb92        sequenceiq/uaa:1.8.1-v2        "/tmp/run.sh"          2 minutes ago       Up 2 minutes               0.0.0.0:8089->8080/tcp                                                                                 cbreak_identity_1        
5e1aa5e984bc        sequenceiq/socat:latest        "socat -u TCP-LISTEN   2 minutes ago       Up 2 minutes               0.0.0.0:32770->3333/tcp                                                                                cbreak_logsink_1         
a4a090904531        gliderlabs/logspout:master     "/bin/sh -c 'sleep 1   2 minutes ago       Up 2 minutes               8000/tcp, 0.0.0.0:8001->80/tcp                                                                         cbreak_logspout_1        
b5f1309b36cb        sequenceiq/ambassadord:0.5.0   "/start --setup-ipta   2 minutes ago       Exited (0) 2 minutes ago                                                                                                          cbreak_ambassadorips_1   
d5d83bdb39ba        sequenceiq/sultans-bin:1.0.1   "/sultans/start-dock   2 minutes ago       Up 2 minutes               3001/tcp, 0.0.0.0:3001->3000/tcp                                                                       cbreak_sultans_1         
351d0e02e87a        sequenceiq/periscope:0.5.6     "/start_periscope_ap   2 minutes ago       Up 2 minutes               0.0.0.0:8085->8080/tcp                                                                                 cbreak_periscope_1       
a59a40f3e912        sequenceiq/pcdb:0.5.6          "/start postgres"      2 minutes ago       Up 2 minutes               172.17.42.1:5433->5432/tcp                                                                             cbreak_pcdb_1            
3be57b3a4753        gliderlabs/registrator:v5      "/bin/registrator co   2 minutes ago       Up 2 minutes                                                                                                                      cbreak_registrator_1     
5eacbb04f38d        sequenceiq/consul:v0.5.0-v3    "/bin/start --server   2 minutes ago       Up 2 minutes               0.0.0.0:8400->8400/tcp, 172.17.42.1:53->53/udp, 8300-8302/tcp, 8301-8302/udp, 0.0.0.0:8500->8500/tcp   cbreak_consul_1          
00967c976bcf        sequenceiq/cbdb:1.0.0          "/start postgres"      2 minutes ago       Up 2 minutes               172.17.42.1:5432->5432/tcp                                                                             cbreak_cbdb_1            
6ef354a1dd75        postgres:9.4.1                 "/docker-entrypoint.   2 minutes ago       Up 2 minutes               172.17.42.1:5434->5432/tcp                                                                             cbreak_uaadb_1           
ae841cd1fe19        sequenceiq/uluwatu-bin:1.0.1   "/uluwatu/start-dock   2 minutes ago       Up 2 minutes               0.0.0.0:3000->3000/tcp                                                                                 cbreak_uluwatu_1         
f1331be5b601        sequenceiq/cloudbreak:1.0.0    "/start_cloudbreak_a   2 minutes ago       Up 2 minutes               0.0.0.0:8080->8080/tcp                                                                                 cbreak_cloudbreak_1      
7833960fe3ae        sequenceiq/ambassadord:0.5.0   "/start --omnimode"    2 minutes ago       Up 2 minutes               10000/tcp                                                                                              cbreak_ambassador_1
```

The logs of cbreak_uaadb_1 show nothing wrong:

```
docker logs cbreak_uaadb_1
LOG:  database system was interrupted; last known up at 2015-07-29 13:32:39 UTC
LOG:  database system was not properly shut down; automatic recovery in progress
LOG:  record with zero length at 0/16A82B0
LOG:  redo is not required
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
```

I did a little test to try and connect from identity_1 to mydb on port 5432, to check if ambassador relays the connection properly:

```
docker exec -ti cbreak_identity_1 bash
root@14e8f7c0eb92:/# apt-get update     
(...)
root@14e8f7c0eb92:/# apt-get install telnet
(...)
root@14e8f7c0eb92:/# telnet mydb 5432
Trying 172.17.0.67...
Connected to mydb.
Escape character is '^]'.
Connection closed by foreign host.
```

The connection closes immediately after connecting. So here are the logs of ambassador_1:

```
docker logs cbreak_ambassador_1
2015/07/29 15:13:44 Ambassadord listening on 10000 using omnimode ...
2015/07/29 15:14:10 dns: read udp 172.17.42.1:53: no route to host
2015/07/29 15:14:10 No backends! Closing the connection
(...)
2015/07/29 15:19:20 dns: read udp 172.17.42.1:53: no route to host
2015/07/29 15:19:20 No backends! Closing the connection
2015/07/29 15:19:30 dns: read udp 172.17.42.1:53: no route to host
2015/07/29 15:19:30 No backends! Closing the connection
2015/07/29 15:19:30 dns: read udp 172.17.42.1:53: no route to host
2015/07/29 15:19:30 No backends! Closing the connection
```

Looks like it cannot connect to docker0. Let's check that:

```
docker exec -ti cbreak_ambassador_1 bash
vi /etc/resolv.conf 
    nameserver 8.8.8.8 (ADDED for apt-get)
    nameserver 172.17.42.1
    search dedibox.fr
root@7833960fe3ae:/# apt-get update
(...)
root@7833960fe3ae:/# apt-get install dnsutils
(...)
dig @172.17.42.1 foo
```

That last dig command does not work whereas it does from the host.
So ambassador needs to talk to consul via DNS but cannot from its container.

That's as far as I got for the moment.

**Comment by biharitomi** [comment]
Hi @francoisprunier ,

It looks like the ambassador could not route the request to the requested backend that should be a '\*.service.consul' domain name in our case, so I assume that something happen with Consul.
Could you please send the logs of the ***'cbreak_consul_1'*** container?

**Comment by francoisprunier** [comment]
Here are the logs:

```
docker logs cbreak_consul_1
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> WARNING: It is highly recommended to set GOMAXPROCS higher than 1
==> Starting Consul agent...
==> Starting Consul agent RPC...
==> Consul agent running!
         Node name: 'node1'
        Datacenter: 'dc1'
            Server: true (bootstrap: true)
       Client Addr: 0.0.0.0 (HTTP: 8500, HTTPS: -1, DNS: 53, RPC: 8400)
      Cluster Addr: 172.17.42.1 (LAN: 8301, WAN: 8302)
    Gossip encrypt: false, RPC-TLS: false, TLS-Incoming: false
             Atlas: <disabled>

==> Log data will now stream in as it occurs:

    2015/07/30 08:26:03 [INFO] serf: EventMemberJoin: node1 172.17.42.1
    2015/07/30 08:26:03 [INFO] serf: EventMemberJoin: node1.dc1 172.17.42.1
    2015/07/30 08:26:03 [INFO] raft: Node at 172.17.42.1:8300 [Follower] entering Follower state
    2015/07/30 08:26:03 [INFO] consul: adding server node1 (Addr: 172.17.42.1:8300) (DC: dc1)
    2015/07/30 08:26:03 [INFO] consul: adding server node1.dc1 (Addr: 172.17.42.1:8300) (DC: dc1)
    2015/07/30 08:26:04 [ERR] agent: failed to sync remote state: No cluster leader
    2015/07/30 08:26:05 [WARN] raft: Heartbeat timeout reached, starting election
    2015/07/30 08:26:05 [INFO] raft: Node at 172.17.42.1:8300 [Candidate] entering Candidate state
    2015/07/30 08:26:05 [INFO] raft: Election won. Tally: 1
    2015/07/30 08:26:05 [INFO] raft: Node at 172.17.42.1:8300 [Leader] entering Leader state
    2015/07/30 08:26:05 [INFO] consul: cluster leadership acquired
    2015/07/30 08:26:05 [INFO] consul: New leader elected: node1
    2015/07/30 08:26:05 [INFO] raft: Disabling EnableSingleNode (bootstrap)
    2015/07/30 08:26:05 [INFO] consul: member 'node1' joined, marking health alive
    2015/07/30 08:26:06 [INFO] agent: Synced service 'consul'
    2015/07/30 08:26:07 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_consul_1:8400'
    2015/07/30 08:26:07 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_consul_1:8500'
    2015/07/30 08:26:07 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_consul_1:53:udp'
    2015/07/30 08:26:07 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_cbdb_1:5432'
    2015/07/30 08:26:07 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_uaadb_1:5432'
    2015/07/30 08:26:07 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_uluwatu_1:3000'
    2015/07/30 08:26:07 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_cloudbreak_1:8080'
    2015/07/30 08:26:08 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_pcdb_1:5432'
    2015/07/30 08:26:10 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_periscope_1:8080'
    2015/07/30 08:26:13 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_sultans_1:3000'
    2015/07/30 08:26:17 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_logspout_1:80'
    2015/07/30 08:26:19 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_logsink_1:3333'
    2015/07/30 08:26:21 [INFO] agent: Synced service 'b05f9996f4f5:cbreak_identity_1:8080'
```

By the way, here's my docker version if it can help:

```
docker --version
Docker version 1.7.1, build 786b29d
```

**Comment by biharitomi** [comment]
It looks good.
Have you tried recreate the containers of the deployment by running **'cbd kill'**, **'cbd regenerate'** and **'cbd start'** commands?
Please share the version of Centos 7 that you are using for further investigation!

**Comment by francoisprunier** [comment]
Yup, I did many installs. I tried initially in virtualbox, then on a barebone machine. 

Just tried again now the sequence kill, regenerate and start but it didn't work.

''''
cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core)

uname -r
3.10.0-229.7.2.el7.x86_64
'''

The system is up to date with the latest updates. I'm going to try to downgrade docker to 1.6 and see if I've got the same issue.

**Comment by biharitomi** [comment]
I think the docker downgrade is not necessary.
Because one of our environment is really similar to that:
$ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): linux/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
$ cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
$ uname -r
3.10.0-229.4.2.el7.x86_64

Is SeLinux enabled on your machine?
This is not the best practice but if its enabled please try to disable it or at least set its state to permissive.

I give a try to a deployment with a machine that has the same version of kernel as you have.

**Comment by francoisprunier** [comment]
Indeed, tried with docker 1.6.2 and it failed as well.

SELinux is disabled:

```
sestatus
SELinux status:                 disabled
```

So far, the only difference is you have a slightly older kernel and a slightly older docker version.

I'm back with docker 1.7.1
```
docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

The CentOS install is the standard one, nothing special was changed.

**Comment by francoisprunier** [comment]
Got it ! It's firewalld that's the problem apparently. I disabled it, restarted the docker daemon to have the iptables rules for docker recreated and it worked !
